### ISSUE TITLE
Please include LICENSE.TXT

### ISSUE THREAD

**Issue by chintan3100** [Glench/fuzzyset.js#47]

**Comment by Glench** [comment]
Hey, I included a license! Thanks for the issue.

**Comment by chintan3100** [comment]
@Glench : I guess this is the port of BSD license of Fuzzy python. I guess you can't change the ported library license?

**Comment by Glench** [comment]
Well first it’s not clear to me that ports of BSD-licensed software actually fall under BSD since the source code is actually different. And second, at this point the library is changed significantly enough that I would no longer describe it as a “port” — not only is the functionality somewhat different but I’ve also added significant contributions. So at least for now I’m relicensing.

**Comment by pombredanne** [comment]
@Glench FWIW, if this is derived, a lawyer and a judge may have a different opinion ;)
